[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"
authors = ["Joseph Caulfield jcaulfield135@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
